USE [master]
GO

/****** Object:  Database [db_stock]    Script Date: 27/03/2020 07:22:31 ******/
CREATE DATABASE [db_stock]
GO

ALTER DATABASE [db_stock] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_stock].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_stock] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_stock] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_stock] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_stock] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_stock] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_stock] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_stock] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_stock] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_stock] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_stock] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_stock] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_stock] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_stock] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_stock] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_stock] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_stock] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_stock] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_stock] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_stock] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_stock] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_stock] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_stock] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_stock] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_stock] SET  MULTI_USER 
GO

ALTER DATABASE [db_stock] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_stock] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_stock] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_stock] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [db_stock] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_stock] SET  READ_WRITE 
GO


